- name: install applications
  homebrew_cask:
    accept_external_apps: yes
    name:
      - freeplane
      - chatgpt
      - reader
#      - roam-research
#      - obsidian
#      - logseq
#      - tiddly
#      - evernote
#      - skitch
#      - papers
#      - kindle
#      - anki

# Have to install tana, readwise reader,  manually

- name: unquarantine freeplane
  command: xattr -r -d com.apple.quarantine /Applications/Freeplane.app
  become: true

#- name: install tools from Mac App Store
#  shell: "mas list | grep \"{{ item }}\" || mas search \"{{ item }}\" | grep \"{{ item }}\" | head -n 1 | awk '{print $1}' | xargs mas install"
#  args:
#      executable: /bin/bash
#  with_items:
#    - Notability
#    - Drafts
#    - Day One
