- name: install applications
  homebrew_cask:
    name: spotify
    install_options: force

- name: un-quarantine Spotify
  shell: xattr -d com.apple.quarantine /Applications/Spotify.app || true

# https://github.com/Homebrew/homebrew-cask/issues/161665
- name: Lets skip the startuphelper
  shell: "launchctl remove com.spotify.client.startuphelper"
