
- name: create database for sonarqube
  postgresql_db:
    name: sonar
    encoding: UTF-8
    login_user: "{{ ansible_env.USER }}"
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0

- name: create user for sonarqube database
  postgresql_user:
    db: sonar
    login_user: "{{ ansible_env.USER }}"
    encrypted: yes
    name: sonar
    password: sonar
    expires: infinity
    role_attr_flags: NOSUPERUSER

#- name: Create directories for sonarqube volumes
#  become: true
#  file:
#    path: "{{ item }}"
#    state: directory
#    mode: '0775'
#    owner: "{{ ansible_env.USER }}"
#    group: staff
#  with_items:
#    - /opt/sonarqube
#    - /opt/sonarqube/data
#    - /opt/sonarqube/logs
#    - /opt/sonarqube/extensions

#- name: pull sonarqube docker image
#  docker_image:
#    name: sonarqube
#    source: pull
#    pull:
#      platform: linux/amd64

- name: install and run sonarqube docker container
  docker_container:
    name: sonarqube
    image: mwizner/sonarqube:8.9.5-community
    state: started
    pull: no
    ports:
      - "9000:9000"
      - "9092:9092"
#    volumes:
#      - /opt/sonarqube/data
#      - /opt/sonarqube/extensions
#      - /opt/sonarqube/logs
    container_default_behavior: compatibility
    env:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
      SONARQUBE_JDBC_URL: "jdbc:postgresql://docker.for.mac.host.internal/sonar"

#- name: stop database server BECAUSE STUPID FP DOCKER PSQL ON STANDARD PORT
#  shell: brew services stop {{ item }}
#  with_items:
#    - postgresql
