- name: setup git - name
  command: git config --global user.name "akafred"

- name: setup git - email
  command: git config --global user.email "github@akafred.com" 

- name: create .gitignore_global
  command: touch {{ ansible_env.HOME }}/.gitignore_global creates={{ ansible_env.HOME }}/.gitignore_global

- name: add entries to .gitignore_global
  lineinfile: dest={{ ansible_env.HOME }}/.gitignore_global line={{ item }}
  with_items:
    - .DS_Store

- name: config to use .gitignore_global
  command: git config --global {{ item }}
  with_items:
    - core.excludesfile ~/.gitignore_global

- name: config push default
  command: git config --global {{ item }}
  with_items:
    - push.default simple

- name: config colors
  command: git config --global {{ item }}
  with_items:
    - color.diff auto
    - color.status auto
    - color.branch auto

- name: config immediate autocorrect
  command: git config --global {{ item }}
  with_items:
    - help.autocorrect '-1'

- name: config aliases
  command: git config --global {{ item }}
  with_items:
    - alias.co checkout
    - alias.ci commit
    - alias.st status
    - alias.br branch
    - alias.hist 'log --pretty=format:"%h %ad | %s%d [%an]" --graph --date=short'
    - alias.type 'cat-file -t'
    - alias.dump 'cat-file -p'
