- name: install applications
  homebrew_cask:
    name:
      - divvy
      - flycut
    install_options: force

- name: install apps from Mac App Store
  shell: "mas list | grep \"{{ item }}\" || mas search \"{{ item }}\" | grep \"{{ item }}\" | head -n 1 | awk '{print $1}' | xargs mas install"
  args:
      executable: /bin/bash
  with_items:
    - Amphetamine
    - Pocket
    - Todoist
