- name: remove obsolete applications
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - alfred
    - jumpcut
    - rightzoom
    - caffeine

- name: install applications
  package:
    name: "{{ item }}"
  ignore_errors: yes
  with_items:
    - divvy
    - flycut

- name: install apps from Mac App Store
  shell: "mas list | grep \"{{ item }}\" || mas search \"{{ item }}\" | grep \"{{ item }}\" | head -n 1 | awk '{print $1}' | xargs mas install"
  args:
      executable: /bin/bash
  with_items:
    - Amphetamine
    - Pocket
