- name: install applications
  homebrew_cask:
    name:
#      - divvy - needs rosetta
      - flycut
      - raycast
      - jordanbaird-ice
    install_options: force

- name: install apps from Mac App Store
  shell: "mas list | grep \"{{ item }}\" || mas search \"{{ item }}\" | grep \"{{ item }}\" | head -n 1 | awk '{print $1}' | xargs mas install"
  args:
      executable: /bin/bash
  with_items:
    - Amphetamine
#    - Todoist

#- name: uninstall apps from Mac App Store # sudo mas uninstall does not work!
#  become: true
#  shell: "mas list | grep \"{{ item }}\" && mas search \"{{ item }}\" | grep \"{{ item }}\" | head -n 1 | awk '{print $1}' | xargs mas uninstall"
#  args:
#    executable: /bin/bash
#  with_items:
#    - Pocket

