- name: remove obsolete applications
  homebrew_cask:
    name: "{{ item }}"
    state: absent
  with_items:
    - alfred
    - jumpcut
    - rightzoom
    - caffeine

- name: install applications
  homebrew_cask:
    name: "{{ item }}"
    accept_external_apps: yes
  with_items:
    - divvy
    - flycut

- name: install apps from Mac App Store
  shell: "mas list | grep {{ item }} || mas search {{ item }} | grep {{ item }} | awk '{print $1}' | xargs mas install"
  args:
      executable: /bin/bash
  with_items:
    - Amphetamine
