- name: install applications
  command: /usr/local/bin/brew cask install {{ item }} creates=/opt/homebrew-cask/Caskroom/{{ item }}
  with_items:
    - alfred
    - caffeine
    - divvy
    - jumpcut
    - rightzoom

