- name: install cloud storage applications
  homebrew_cask:
    name:
      - Dropbox
    install_options: force
#    - google-backup-and-sync

- name: allow Dropbox
  shell: "xattr -d com.apple.quarantine /Applications/Dropbox.app || true"

