- name: docker for mac
  homebrew_cask:
    name: docker
  when: ansible_processor != 'Apple M1'
  # Man kan manuelt installere Docker på Apple M1:
  # https://docs.docker.com/docker-for-mac/apple-m1/

- name: install pip for system-python (used by ansible locally)
  command: "{{ansible_python_interpreter}} -m ensurepip --default-pip"
  become: true

- name: remove deprecated docker-py for system python
  pip:
    name: docker-py
    executable: "{{ansible_python_interpreter}} -m pip"
    state: absent
  ignore_errors: yes
  become: true

- name: install docker for system python (used by ansible locally)
  command: "{{ansible_python_interpreter}} -m pip --no-cache install docker"
  become: true
