- name: docker for mac
  homebrew_cask:
    name: docker

- name: install pip for system-python (used by ansible locally)
  command: "{{ansible_python_interpreter}} -m ensurepip --default-pip"
  become: true

- name: install docker for system python (used by ansible locally)
  command: "{{ansible_python_interpreter}} -m pip --no-cache install docker"
  become: true
