
 - name: install virtualbox
   become: true
   homebrew_cask: name={{ item }}
   with_items:
     - virtualbox

 - name: install vagrant
   homebrew_cask: name={{ item }}
   with_items:
     - vagrant

# Need to fix the version number
 - name: install vagrant plugin for caching
   command: /usr/bin/vagrant plugin install vagrant-cachier creates=.vagrant.d/gems/gems/vagrant-cachier-0.6.0
