- name: install mysql
  homebrew: name={{ item }}
  with_items:
    - mysql

- name: start mysql on boot
  shell: brew services start {{ item }}
  with_items:
    - mysql

- name: install sequel pro (mac mysql client)
  package: name={{ item }}
  with_items:
    - sequel-pro
