- name: install applications
  homebrew_cask:
    name:
      - obs
      - obs-virtualcam
      - elgato-stream-deck
      - epoccam
      - logitech-camera-settings
#    - loopback - costs money

#- name: install apps from Mac App Store
#  shell: "mas list | grep \"{{ item }}\" || mas search \"{{ item }}\" | grep \"{{ item }}\" | head -n 1 | awk '{print $1}' | xargs mas install"
#  args:
#      executable: /bin/bash
#  with_items:
#    - Backdrop
#    # - EpocCam WebCam Viewer - haven't seen this work
