- name: install applications
  homebrew_cask:
    name:
      - obs
      - obs-virtualcam
#    - loopback - costs money

- name: install Backdrop
  shell: mas list | grep 411461952 || mas install 411461952
