- name: install applications
  homebrew_cask:
    name: "{{ item }}"
  ignore_errors: yes
  with_items:
    - obs
    - obs-virtualcam
#    - loopback - costs money

- name: install Backdrop
  shell: mas list | grep 411461952 || mas install 411461952
