- name: install applications
  homebrew_cask: name={{ item }}
  ignore_errors: yes
  with_items:
#    - tiddly
#    - evernote
#    - skitch
    - freemind
#    - papers
#    - vitamin-r
    - kindle
    - selfcontrol
#    - anki

# mas search todoist -
- name: install todoist
  shell: mas list | grep 585829637 || mas install 585829637
  args:
    executable: /bin/bash
