
- name: install applications
  package:
    name: "{{ item }}"
  ignore_errors: yes
  with_items:
#    - hipchat
    - skype
    - slack

#- name: BlueJeans
#  package: name={{ item }} state=absent
#  with_items:
#    - blue-jeans-launcher
