
- name: install applications
  homebrew_cask: name={{ item }}
  with_items:
#    - hipchat
    - skype
    - slack

- name: BlueJeans
  homebrew_cask: name={{ item }}
  with_items:
    - blue-jeans-launcher
