
- name: install applications
  homebrew_cask:
    name:
#      - skype
      - slack
#      - whatsapp
      - zoom
#      - mural
#      - roam-research
    accept_external_apps: yes

## Install Roam from dmg manually
#
#- local_action: stat path="/Applications/Roam Research.app"
#  register: app_exists
#
#- command: mkdir -p ./tmp/
#  when: app_exists.stat.exists == False
#
#- get_url: url=https://roam-electron-deploy.s3.us-east-2.amazonaws.com/Roam+Research-0.0.13.dmg dest=./tmp/Roam+Research.dmg
#  when: app_exists.stat.exists == False
#
#- command: hdiutil attach ./tmp/Roam+Research.dmg -nobrowse -mountpoint ./tmp/Roam+Research
#  when: app_exists.stat.exists == False
#
#- shell: cp -aR ./tmp/Roam+Research/*.app "/Applications/Roam Research.app"
#  when: app_exists.stat.exists == False
#
#- command: hdiutil detach ./tmp/Roam+Research/
#  when: app_exists.stat.exists == False
#
#- command: rm -R ./tmp/
#  when: app_exists.stat.exists == False
