
- name: install applications
  homebrew_cask: name={{ item }}
  ignore_errors: yes
  with_items:
#    - hipchat
    - skype
    - slack

#- name: BlueJeans
#  homebrew_cask: n<me={{ item }} state=absent
#  with_items:
#    - blue-jeans-launcher
