
- name: install applications
  homebrew_cask:
    name:
      - skype
      - slack
      - whatsapp
      - zoom
    accept_external_apps: yes

# Install Mural from dmg

- local_action: stat path=/Applications/Mural.app
  register: app_exists

- command: mkdir -p ./tmp/
  when: app_exists.stat.exists == False

- get_url: url=https://download.mural.co/mac-app/MURAL-1.0.10.dmg dest=./tmp/Mural.dmg
  when: app_exists.stat.exists == False

- command: hdiutil attach ./tmp/Mural.dmg -nobrowse -mountpoint ./tmp/Mural
  when: app_exists.stat.exists == False

- shell: cp -aR ./tmp/Mural/*.app /Applications/Mural.app
  when: app_exists.stat.exists == False

- command: hdiutil detach ./tmp/Mural/
  when: app_exists.stat.exists == False

- command: rm -R ./tmp/
  when: app_exists.stat.exists == False
