
- name: install applications
  command: /usr/local/bin/brew cask install {{ item }} creates=/opt/homebrew-cask/Caskroom/{{ item }}
  with_items:
    - sublime-text

- name: install sublime-text executable soft link
  file: >
    src="{{ ansible_env.HOME }}/Applications/Sublime Text 2.app/Contents/SharedSupport/bin/subl"
    dest={{ ansible_env.HOME }}/bin/subl
    mode=0750
    state=link

- name: copy my settings files to sublime-text
  copy: >
    src={{ item }} 
    dest="{{ ansible_env.HOME }}/Library/Application Support/Sublime Text 2/Packages/User/"
  with_items:
    - Preferences.sublime-settings
    - groovy.sublime-build
