
- name: install applications
  homebrew_cask: name={{ item }}
  with_items:
    - sublime-text

- name: install sublime-text executable soft link
  file: >
    src="{{ ansible_env.HOME }}/Applications/Sublime Text 2.app/Contents/SharedSupport/bin/subl"
    dest={{ ansible_env.HOME }}/bin/subl
    mode=0750
    state=link

- name: copy my settings files to sublime-text
  copy: >
    src={{ item }} 
    dest="{{ ansible_env.HOME }}/Library/Application Support/Sublime Text 2/Packages/User/"
  with_items:
    - Preferences.sublime-settings
    - groovy.sublime-build

- name: download package control 
  get_url: >
    url="https://packagecontrol.io/Package Control.sublime-package"
    dest="{{ ansible_env.HOME }}/Library/Application Support/Sublime Text 2/Installed Packages/"
    sha256sum="eb2297e1a458f27d836c04bb0cbaf282d0e7a3098092775ccb37ca9d6b2e4b7d"
