
- name: install applications
  homebrew_cask: name={{ item }}
  ignore_errors: yes
  with_items:
    - sublime-text

- name: install sublime-text executable soft link
  file: >
    src="{{ ansible_env.HOME }}/Applications/Sublime Text 2.app/Contents/SharedSupport/bin/subl"
    dest={{ ansible_env.HOME }}/bin/subl
    mode=0750
    state=link

- name: copy my settings files to sublime-text
  copy: >
    src={{ item }} 
    dest="{{ ansible_env.HOME }}/Library/Application Support/Sublime Text 2/Packages/User/"
  with_items:
    - Preferences.sublime-settings
    - groovy.sublime-build

- name: download package control 
  get_url: >
    url="https://packagecontrol.io/Package Control.sublime-package"
    dest="{{ ansible_env.HOME }}/Library/Application Support/Sublime Text 2/Installed Packages/"
    sha256sum="2915d1851351e5ee549c20394736b4428bc59f460fa1548d1514676163dafc88"
