
# From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/go.rb
#==> Options
#--cross-compile-all
#	Build the cross-compilers and runtime support for all supported platforms
#--cross-compile-common
#	Build the cross-compilers and runtime support for darwin, linux and windows
#--without-cgo
#	Build without cgo
#--HEAD
#	install HEAD version
#==> Caveats
#As of go 1.2, a valid GOPATH is required to use the `go get` command:
#  http://golang.org/doc/code.html#GOPATH
#
#`go vet` and `go doc` are now part of the go.tools sub repo:
#  http://golang.org/doc/go1.2#go_tools_godoc
#
#To get `go vet` and `go doc` run:
#  go get code.google.com/p/go.tools/cmd/godoc
#  go get code.google.com/p/go.tools/cmd/vet
#
#You may wish to add the GOROOT-based install location to your PATH:
#  export PATH=$PATH:/usr/local/opt/go/libexec/bin

- name: Install go 
  homebrew: name=go install_options=cross-compile-common

- name: add go to path
  become: true
  lineinfile: >
    dest=/etc/paths.d/90-golang-bin
    line=/usr/local/opt/go/libexec/bin
    regexp=/usr/local/opt/go/libexec/bin
    create=yes
