- name: Install go 
  homebrew: name=go

- name: add go to path
  become: true
  lineinfile: >
    dest=/etc/paths.d/90-golang-bin
    line=/usr/local/opt/go/libexec/bin
    regexp=/usr/local/opt/go/libexec/bin
    create=yes
