- name: Make hidden files visible
  osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: true
    state: present
  register: default_set_visible

- name: Make all extensions visible
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true
    state: present
  register: default_set_extension

- name: restart Finder
  command: killall Finder
  when: default_set_visible.changed or default_set_extension.changed
