- name: Make hidden files visible
  osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: true
    state: present
  register: default_set_visible

- name: Make all extensions visible
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true
    state: present
  register: default_set_extension

- name: restart Finder
  command: killall Finder
  when: default_set_visible.changed or default_set_extension.changed

- name: get dock-removal-script in place
  copy:
    src: remove-dock-app.sh
    dest: "{{ ansible_env.HOME }}/bin/remove-dock-app.sh"
    owner: "{{ ansible_env.USER }}"
    group: staff
    mode: 0750

- name: remove dock apps
  shell: "{{ ansible_env.HOME }}/bin/remove-dock-app.sh {{ item }}"
  with_items:
    - Messages
    - Meldinger
    - Mail
    - Maps
    - Kart
    - Photos
    - Bilder
    - FaceTime
    - Calendar
    - Kalender
    - Contacts
    - Kontakter
    - Reminders
    - "Påminnelser"
    - TV
    - Music
    - Musikk
    - Podcasts
    - Keynote
    - Pages
    - Numbers
    - Notes
    - Notater
    - System Preferences
    - Safari
    - App Store
    - Freeform

# Not sure if this works - works on commandline...
- name: autohide dock
  shell: osascript -e "tell application \"System Events\" to set the autohide of the dock preferences to true"
