- name: Make hidden files visible
  osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: true
    state: present
  register: default_set

- name: restart Finder
  command: killall Finder
  when: default_set.changed

