- name: create projects folder
  file:
    path: "{{ ansible_env.HOME }}/Projects/navikt"
    state: directory
    owner: "{{ ansible_env.USER }}"
    mode: 0750

- name: shell-script environment stuff
  copy:
    src: nav_shellrc.sh
    dest: "{{ ansible_env.HOME }}/.nav_shellrc.sh"

- name: init nav environment
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.paths_homes_etc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK for Nav environment"
    content: "source {{ ansible_env.HOME }}/.nav_shellrc.sh"

- name: update hosts-file
  become: true
  blockinfile:
    dest: /etc/hosts
    marker: "# {mark} ANSIBLE MANAGED BLOCK for Nav environment"
    content: |
             127.0.0.1  someservice.nav.no

- name: create nav-profile-for-git
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    owner: "{{ ansible_env.USER }}"
    mode: 0640
  with_items:
    - "Projects/navikt/.gitconfig-nav"

- name: add nav-profile-for-git
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.gitconfig"
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK for Nav environment"
    content: |
             [includeIf "gitdir:Projects/navikt/"]
                     path = ~/Projects/navikt/.gitconfig-nav

- name: ensure .ssh/config exists
  copy:
    content: ""
    force: no
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    owner: "{{ ansible_env.USER }}"
    mode: 0600

- name: create .ssh/config.d
  file:
    path: "{{ ansible_env.HOME }}/.ssh/config.d"
    state: directory
    owner: "{{ ansible_env.USER }}"
    mode: 0750

- name: create nav config file
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    owner: "{{ ansible_env.USER }}"
    mode: 0600
  with_items:
    - ".ssh/config.d/nav"

- name: make sure .ssh-config has nav stuff
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    insertbefore: BOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK for Nav environment"
    content: Include ~/.ssh/config.d/*

- name: create nav maven settings file
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    owner: "{{ ansible_env.USER }}"
    mode: 0600
  with_items:
    - ".m2/navikt-settings.xml"

#- name: create nav security file
#  copy:
#    src: "{{ item }}"
#    dest: "{{ ansible_env.HOME }}/{{ item }}"
#    owner: "{{ ansible_env.USER }}"
#    mode: 0600
#  with_items:
#    - ".m2/settings-security.xml"

- name: copy proxy cert
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    owner: "{{ ansible_env.USER }}"
    mode: 0600
  with_items:
    - "proxy.cer"

- name: Import certificate to a given cacerts keystore
  become: true
  java_cert:
    cert_path: "{{ ansible_env.HOME }}/proxy.cer"
    cert_alias: webproxy
    executable: "{{ item }}/bin/keytool"
    keystore_path: "{{ item }}/lib/security/cacerts"
    keystore_pass: changeit
    state: present
  with_items:
    - "/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre"
    - "/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home"
    - "/Library/Java/JavaVirtualMachines/openjdk-13.0.1.jdk/Contents/Home"

- name: setup mvn settings
  lineinfile:
    path: "{{ ansible_env.HOME }}/.m2/bin/mvn"
    regexp: "    \\*\\/navikt\\*\\).*;;"
    insertafter: '.*# options here:$'
    line: '    */navikt*)              SETTINGS="navikt-settings.xml" ;;'

- name: add tunneling for some repos to maven
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.paths_homes_etc"
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK for Maven in Nav-environment"
    content: |
             export MAVEN_OPTS='-Djava.net.useSystemProxies=true'

  #  export MAVEN_OPTS='-DsocksProxyHost=127.0.0.1 -DsocksProxyPort=14122 -DsocksNonProxyHosts=127.0.0.1|dl.bintray.com|repo.maven.apache.org|*.local|169.254/16|raw.githubusercontent.com|cache-redirector.jetbrains.com|*.cloudfront.net|*.confluent.io|*.gradle.org|*.apache.org|*.bintray.com|repo.jfrog.org|maven.pkg.github.com'

- name: create .gradle folder
  file:
    path: "{{ ansible_env.HOME }}/.gradle"
    state: directory
    owner: "{{ ansible_env.USER }}"
    mode: 0750

- name: ensure .gradle/gradle.properties
  copy:
    content: ""
    force: no
    dest: "{{ ansible_env.HOME }}/.gradle/gradle.properties"
    owner: "{{ ansible_env.USER }}"
    mode: 0600

- name: make sure .gradle/gradle.properties has nav stuff
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.gradle/gradle.properties"
    insertbefore: BOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK for Nav environment"
    block: |
      # Putt disse i Network - Bypass proxy settings for these Hosts & Domains:
      # *.local, 169.254/16, raw.githubusercontent.com, cache-redirector.jetbrains.com, *.cloudfront.net, *.confluent.io, *.gradle.org, *.apache.org, *.bintray.com, repo.jfrog.org, nvd.nist.gov
      org.gradle.jvmargs=-DsocksProxyHost=127.0.0.1 -DsocksProxyPort=14122

- name: make sure .gradle/gradle.properties has Github Package Repo stuff
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.gradle/gradle.properties"
    insertbefore: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK for Github Package Repo"
    block: "{{lookup('file', 'gpr-content')}}"

- name: Install kubectl
  homebrew:
    name: kubectl
    state: present

- name: Get kubeconfig from github
  git:
    repo: 'git@github.com-kjetiljd:navikt/kubeconfigs.git'
    dest: "{{ ansible_env.HOME }}/Projects/navikt/kubeconfigs"
    update: no

- name: KUBECONFIG environment variable
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.paths_homes_etc"
    line: export KUBECONFIG="{{ ansible_env.HOME }}/Projects/navikt/kubeconfigs/config"
    regexp: export KUBECONFIG

- name: Create a symbolic link
  file:
    src: "{{ ansible_env.HOME }}/Projects/navikt/kubeconfigs/config"
    dest: "{{ ansible_env.HOME }}/.kube/config"
    owner: "{{ ansible_env.USER }}"
    state: link

# https://github.com/boz/kail
- name: Get homebrew repo for kail
  homebrew_tap:
    name: boz/repo

- name: Get kail
  homebrew:
    name:  boz/repo/kail
    state: present

- name: Get kubernetic
  homebrew_cask:
    name: kubernetic
    state: present

- name: Get kube-ps1
  homebrew:
    name: kube-ps1
    state: present
