- name: install sourcetree
  homebrew_cask: name={{ item }}
  with_items:
    - sourcetree


- name: install gource - https://code.google.com/p/gource/
  homebrew: name={{ item }}
  with_items:
   - gource
