# Prereqs:
#     Run .provisioning/bootstrap.sh
#
# A symlink is nice:
#     ln -s `pwd`/.provisioning ~/.provisioning
# Then you can run this setup with:
#     pushd ~/.provisioning/ && ansible-playbook -Kv ohmyimac.yml ; popd
#

- hosts: localhost
  roles:
    - shell-config
    - perfectly_brewed
    - git-mods
#    - altident
    - os-adjustments
    - personal-bin
    - cli-tools
    - zshell
    - app-storable
#    - cloudy
    - productivity
#    - msoffice
    - atomic
    - collaborative
    - browsers_and_tweaks
    - a_more_usable_ui
    - fonts
    - idea
    - java-development
#    - dockered
#    - kubernetes
    - os-tools
#    - spotify
    - postgresql-y
#    - dockered_sonarqube
#    - nav
#    - remoting
#    - python-development
#    - screencasting
#    - displaylink
#    - machine-learning
#    - js-development
#    - cronable
#    - salty
#    - asciidoc
#    - sublime
#    - emacs
#    - r-development
#    - app-engine-development
    - groovy-development
#    - android-development
    - kotlin-development
#    - scala-development
#    - clojure-development
#    - golang-development
#    - ruby-development
    - elm-development
#    - my-sequel
#    - ipad-integration
#    - steamy
#    - vagrantready
#    - duckdns
#    - experimental
