# Prereqs:
#     Run .provisioning/bootstrap.sh
#
# A symlink is nice:
#     ln -s `pwd`/.provisioning ~/.provisioning
# Then you can run this setup with:
#     pushd ~/.provisioning/ && ansible-playbook -Kv ohmynavm1.yml ; popd
#

- hosts: localhost
  vars:
    ansible_pkg_mgr: Homebrew
  roles:
    - shell-config
    - perfectly_brewed
    - os-adjustments
    - zshell
    - personal-bin
    - cli-tools
    - app-storable
    - productivity
    - msoffice
    - atomic
    - collaborative
    - a_more_usable_ui
    - app-store-apps
    - remoting
    - fonts
    - git-mods
    - idea
    - java-development
    - altident
#    - os-tools
#    - cronable
#    - salty
#    - asciidoc
    - dockered
    - browsers_and_tweaks
#    - sublime
#    - emacs
#    - cloudy
#    - r-development
#    - machine-learning
#    - app-engine-development
#    - groovy-development
#    - android-development
#    - kotlin-development
#    - scala-development
#    - clojure-development
#    - golang-development
    - js-development
#    - python-development
#    - ruby-development
#    - my-sequel
    - postgresql-y
    - dockered_sonarqube
    - screencasting
#    - ipad-integration
#    - steamy
#    - vagrantready
    - spotify
    - nav
#    - experimental
