# # # # # # # # # # # # # # #
#
# After changing this file you need to run:
#
#    ansible-galaxy install -r requirements.yml --force

# Example:
collections:
  - name: community.general
    version: '*'
