- name: install Javas
  homebrew_cask:
    name: "{{ item }}"
  with_items:
#    - java6
    - java8
    - java

- name: install maven
  homebrew: name=maven

- name: create mvn settings bin-folder
  file:
    path: "{{ ansible_env.HOME }}/.m2/bin"
    state: directory
    mode: 0755

- name: use my smart mvn command
  copy: >
    src={{ item.name }}
    dest="{{ ansible_env.HOME }}/{{ item.name }}"
    mode="{{ item.mode }}"
    owner="{{ ansible_env.USER }}"
    group="staff"
  with_items:
    - { name: ".m2/bin/mvn", mode: 'u=rwx,g=rx,o=r' }
    - { name: ".m2/default-settings.xml", mode: 'u=rw,g=r,o=' }
    # - { name: ".m2/something-settings.xml", mode: 'u=rw,g=r,o=' }

- name: override mvn command
  lineinfile: >
    dest={{ ansible_env.HOME }}/.paths_homes_etc
    line='PATH={{ ansible_env.HOME }}/.m2/bin:$PATH'
    regexp='PATH={{ ansible_env.HOME }}\/\.m2/bin:\$PATH'

- name: add java_ls and java_use commands
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.paths_homes_etc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK for java commands"
    content: |
             alias java_ls='/usr/libexec/java_home -V 2>&1 | grep -E "\d\d?(?:(?:.\d)?.\d[,_])?," | cut -d , -f 1 | colrm 1 4 | grep -v Home'
             function java_use() {
                 export JAVA_HOME=$(/usr/libexec/java_home -v $1)
                 export PATH=$JAVA_HOME/bin:$PATH
                 java -version
             }

- name: set default java
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.paths_homes_etc"
    insertafter: EOF
    line: "java_use 1.8"
    regexp: "^java_use"
