- name: install intellij
  homebrew_cask: name={{ item }}
  with_items:
    - intellij-idea

- name: install old casks (for java 7)
  command: >
    /usr/local/bin/brew tap caskroom/homebrew-versions
    creates=/usr/local/Library/Taps/caskroom/homebrew-versions

- name: install java7 for appengine development
  homebrew_cask: name={{ item }}
  with_items:
    - java7


- name: install AppEngine SDK for Java
  homebrew: name={{ item }}
  with_items:
    - app-engine-java-sdk

# - name: install maven
#  homebrew: name=maven

# - name: intellij doesnt start with java 1.7
# /opt/homebrew-cask/Caskroom/intellij-idea/13.1.1/IntelliJ IDEA 13.app/Contents/Info.plist
#      <key>JVMVersion</key>
#      <string>1.6*</string>
# Need to change to 1.7*  - now done manually...

- name: add java_ls and java_use commands
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.paths_homes_etc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK for java commands"
    content: |
             alias java_ls='/usr/libexec/java_home -V 2>&1 | grep -E "\d.\d.\d[,_]" | cut -d , -f 1 | colrm 1 4 | grep -v Home'
             function java_use() {
                 export JAVA_HOME=$(/usr/libexec/java_home -v $1)
                 export PATH=$JAVA_HOME/bin:$PATH
                 java -version
             }
