- name: install intellij
  homebrew_cask: name={{ item }}
  ignore_errors: yes
  with_items:
    - intellij-idea

- name: install old casks (for old javas)
  homebrew_tap: name=caskroom/homebrew-versions

- name: install Javas
  homebrew_cask:
    name: "{{ item }}"
  ignore_errors: yes
  with_items:
    - java7
    - java8
    - java9
    - java

- name: install maven
  homebrew: name=maven

- name: add java_ls and java_use commands
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.paths_homes_etc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK for java commands"
    content: |
             alias java_ls='/usr/libexec/java_home -V 2>&1 | grep -E "\d.\d.\d[,_]" | cut -d , -f 1 | colrm 1 4 | grep -v Home'
             function java_use() {
                 export JAVA_HOME=$(/usr/libexec/java_home -v $1)
                 export PATH=$JAVA_HOME/bin:$PATH
                 java -version
             }
