- name: create bash_profile
  copy:
    content: "" 
    dest: "{{ ansible_env.HOME }}/.bash_profile"
    force: no

- name: create .paths_homes_etc
  copy: 
    content: ""
    dest: "{{ ansible_env.HOME }}/.paths_homes_etc"
    force: no

- name: add paths_homes_etc to bash_profile
  lineinfile: 
    dest: "{{ ansible_env.HOME }}/.bash_profile"
    line: "source ~/.paths_homes_etc"
    regexp: "paths_homes_etc"

- name: detect shell and put in PROFILE_SHELL-variable
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.paths_homes_etc"
    insertbefore: BOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK for detecting shell"
    content: |
             # Determine what (Bourne compatible) shell we are running under. Put the result
             # in $PROFILE_SHELL (not $SHELL) so further code can depend on the shell type.
             if test -n "$ZSH_VERSION"; then
               PROFILE_SHELL=zsh
             elif test -n "$BASH_VERSION"; then
               PROFILE_SHELL=bash
             elif test -n "$KSH_VERSION"; then
               PROFILE_SHELL=ksh
             elif test -n "$FCEDIT"; then
               PROFILE_SHELL=ksh
             elif test -n "$PS3"; then
               PROFILE_SHELL=unknown
             else
               PROFILE_SHELL=sh
             fi

- name: add locale exports
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.paths_homes_etc"
    line: "export {{ item }}"
    regexp: "{{ item }}"
  with_items:
    - "LC_CTYPE=en_US.UTF-8"
    - "LC_ALL=en_US.UTF-8"
