
- name: install other apps from Mac App Store
  shell: "mas list | grep \"{{ item }}\" || mas search \"{{ item }}\" | grep \"{{ item }}\" | head -n 1 | awk '{print $1}' | xargs mas install"
  args:
      executable: /bin/bash
  with_items:
    - Trello
    - iA Writer
    - Notability
    - Backdrop
