
- name: create dotfiles-directory in Dropbox
  file: path={{ ansible_env.HOME }}/Dropbox/dotfiles/{{ansible_user_id}}/dotfiles state=directory

- name: create rsync-exclude-file
  command: touch {{ ansible_env.HOME }}/.rsync-exclude creates={{ ansible_env.HOME }}/.rsync-exclude

- name: add entries to .rsync-exclude
  lineinfile: dest={{ ansible_env.HOME }}/.rsync-exclude line={{ item }}
  with_items:
    - "*.log"
    - "*.swo"
    - "*.swp"
    - .*.retry
    - .CFUserTextEncoding
    - .DS_Store
    - .RData
    - .Rhistory
    - .Trash
    - .Xauthority
    - .ansible
    - .ansible.cfg
    - .bash_history
    - .bash_profile
    - .bashrc
    - .cache
    - .cups
    - .distlib
    - .dropbox
    - .dropbox-master
    - .freemind
    - .gem
    - .hgignore_global
    - .gitconfig
    - .gitignore_global
    - .grails
    - .grails_history
    - .groovy
    - .gvm
    - .ivy2
    - .lein
    - .lesshst
    - .m2
    - .octave_hist
    - .pgadmin_histoqueries
    - .pgpass
    - .rnd
    - .rstudio-desktop
    - .rsync-exclude
    - .sbt
    - .sbtconfig
    - .scala_history
    - .serverauth.*
    - .ssh
    - .subversion
    - .tapas
    - .vagrant.d
    - .viminfo

- name: setup cron based rsync of dotfiles to Dropbox-dotfiles
  cron: > 
    name="copy dotfiles to Dropbox" 
    minute="*/10" 
    job="/usr/bin/rsync -av --delete --delete-excluded --exclude-from={{ ansible_env.HOME }}/.rsync-exclude {{ ansible_env.HOME }}/.??* {{ ansible_env.HOME }}/Dropbox/dotfiles/{{ansible_user_id}}/dotfiles >> {{ ansible_env.HOME }}/.rsync.log"
