# has been buggy ...
- name: install nova
  homebrew_cask:
    name: nova
  when: ansible_system == 'Darwin'

- name: uninstall atom
  homebrew_cask:
    name: atom
    state: absent

# 
# - name: install atom packages
#   shell: |
#     set -euo pipefail
#     apm list --bare | grep -E '^{{ item }}@' &&
#     echo 'Already installed.' ||
#     apm install '{{ item }}'
#   args:
#     executable: /bin/bash
#   register: apm_result
#   changed_when: "'Already installed.' not in apm_result.stdout"
#   with_items:
#     - sort-lines
#     - wakatime
#     - ansible-vault
#     - git-history
#     - linter
#     - linter-shellcheck
