- name: install zed
  homebrew_cask:
    name:
      - zed
      - github

- name: uninstall passé editors
  homebrew_cask:
    name:
      - atom
      - nova
      - sublime-text
    state: absent
#
# - name: install atom packages
#   shell: |
#     set -euo pipefail
#     apm list --bare | grep -E '^{{ item }}@' &&
#     echo 'Already installed.' ||
#     apm install '{{ item }}'
#   args:
#     executable: /bin/bash
#   register: apm_result
#   changed_when: "'Already installed.' not in apm_result.stdout"
#   with_items:
#     - sort-lines
#     - wakatime
#     - ansible-vault
#     - git-history
#     - linter
#     - linter-shellcheck
