
- name: "install database server (default user for the database is {{ ansible_env.USER }})"
  homebrew:
    name: postgresql@14

- name: start database server automatically
  shell: brew services restart {{ item }}
  with_items:
    - postgresql@14

- name: install pip for system-python (used by ansible locally)
  command: "{{ansible_python_interpreter}} -m ensurepip --default-pip"
  become: true

- name: install Python-PostgreSQL Database Adapter
  command: env LDFLAGS="-I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib" {{ansible_python_interpreter}} -m pip --no-cache install psycopg2
  become: true

- name: install DBeaver (universal sql client)
  homebrew_cask:
    name: dbeaver-community
