
- name: install half decent browser - or two
  command: /usr/local/bin/brew cask install {{ item }} creates=/opt/homebrew-cask/Caskroom/{{ item }}
  with_items:
    - chromium
    - firefox

- name: add firefox to path
  sudo: true
  lineinfile: >
    dest=/etc/paths.d/70-firefox
    line=/opt/homebrew-cask/Caskroom/firefox/latest/Firefox.app/Contents/MacOS
    regexp=.*firefox.*
    mode=0644
    create=yes

- name: install codecs for HTML5 video
  homebrew: name={{ item }}
  with_items:
   - ffmpeg    

- name: install lastpass
  sudo: true
  command: /usr/local/bin/brew cask install {{ item }} creates=/opt/homebrew-cask/Caskroom/{{ item }}
  with_items:
    - lastpass
