
- name: install half decent browser - or two
  homebrew_cask: name={{ item }}
  with_items:
    - chromium
    - firefox
    - google-chrome

- name: add firefox to path
  become: true
  lineinfile: >
    dest=/etc/paths.d/70-firefox
    line=/opt/homebrew-cask/Caskroom/firefox/latest/Firefox.app/Contents/MacOS
    regexp=.*firefox.*
    mode=0644
    create=yes

- name: install codecs for HTML5 video
  homebrew: name={{ item }}
  with_items:
   - ffmpeg    

- name: install lastpass
  homebrew_cask: name={{ item }}
  with_items:
    - lastpass
