
- name: install half decent browser - or two
  homebrew_cask:
    name:
     - firefox
     - microsoft-edge
#     - chromium  does not have sha
#     - google-chrome does not have sha

- name: add firefox to path
  become: true
  lineinfile: >
    dest=/etc/paths.d/70-firefox
    line=/opt/homebrew-cask/Caskroom/firefox/latest/Firefox.app/Contents/MacOS
    regexp=.*firefox.*
    mode=0644
    create=yes

# - name: install codecs for HTML5 video
#  homebrew: name={{ item }}
#  with_items:
#   - ffmpeg

# - name: install lastpass
#  homebrew_cask:
#    name: lastpass does not have sha

#- name: install tweaks from Mac App Store
#  shell: "mas list | grep \"{{ item }}\" || mas search \"{{ item }}\" | grep \"{{ item }}\" | head -n 1 | awk '{print $1}' | xargs mas install"
#  args:
#      executable: /bin/bash
#  with_items:
#    - Super Agent for Safari
