- name: install r using brew - install r
  brew_cask: r


- name: install r using brew - install rstudio
  brew_cask: rstudio

# https://stackoverflow.com/questions/9689104/installing-r-on-mac-warning-messages-setting-lc-ctype-failed-using-c
- name: fix locale-issue
  command: defaults write org.R-project.R force.LANG en_US.UTF-8
