- name: install r using brew - install r
  homebrew_cask: name=r

# https://stackoverflow.com/questions/9689104/installing-r-on-mac-warning-messages-setting-lc-ctype-failed-using-c
- name: fix locale-issue
  command: defaults write org.R-project.R force.LANG en_US.UTF-8
